### ISSUE TITLE
Answer to feedback - Terrorism Group

### ISSUE THREAD

**Issue by paulafortuna** [Rostlab/DM_CS_WS_2016-17#10]
- [x]    Figure in Sec. 1.2: if there is no real meaning in the coloring grading, do not use it. It leads to believe that it represents another variable.

- [x]    Figure in Sec. 1.2: "However, we can see that from 2014 to 2015 this number decreased." that's not the most obvious thing that stands out first from the figure. That sentence would require more information. Furthermore, it's very difficult or impossible to extrapolate a trend form only those 2 years, since in all previous years the attacks decreased. BTW, do you have ALL attacks of 2015 in your dataset ? Do you have attacks of 2016 ?
**Yes. The database is updated every year for the preceding year en masse. Data for 2016 will be available in the middle of 2017** 

- [x]    Make sure your figures are perfectly visible and that the axes are well explained. For example, Fig. Sec1.2, axis y: count? Spell out sth like: "terrorist attacks, count".

- [x]    Adding to the last point, Figures/Tables should be self contained and stand by themselves. Always put a caption explaining what we see or should see and cite the figure/table in the main text.

- [x]    Love the youtube videos. They only go a bit too fast and so are difficult to follow. Perhaps more gradual transitions would ease the interpretation. Also, the legend of used colors is too tiny to notice and by themselves the meaning of the colors is not obvious. Plus, what does the size mean then? That is, explain all your visual cues.

- [x]  Good finding on the apparent error on labels

- [x]    Figure "Type of Attacks evolving since 1970", again the legend is too small to read

    ...didn't go in detail until...:

- [x]    Figure "Number of Kills vs Attack Type" why not just write the attack types labels on the x axis? Very difficult to read, even more considering that the odd but unwritten numbers are actually valid values.

- [x]    Last Figure and all: always provide an explanation --> what do we see here?

- [x]     Figure in Sec 2.2 --> I know what it means, but again, write out all axes meanings -- x axis?

- [x]     AND Always sort frequency histograms. It would make the reading that much easier. Example: from the figure alone, what are the top 3 features with most missing values? Very difficult to answer if it's not sorted.

**Comment by juanmirocks** [comment]
Thanks for this

**Comment by juanmirocks** [comment]
Great. Please close when appropriate
