### ISSUE TITLE
How to run skripts on server without being logged in

### ISSUE THREAD

**Issue by ImkeHelene** [Rostlab/DM_CS_WS_2016-17#11]
Hi @juanmirocks ,

we found a way to install the python pypi google-ngram-dwonloader in an anaconda environment on the server and already have a script that does the cleaning before we save the table there. 
But running the script for downloading and cleaning the bigram files will take a VERY LONG TIME. Since in our group no one has a desktop computer or any computer that they don't need we wanted to ask you if there is a way to run a python script on the server without staying logged in all the time?
Regards,

@brosequartz, @ishaanraj, @ImkeHelene

**Comment by juanmirocks** [comment]
@ImkeHelene what you need is the utility `screen`

google it :)
