### ISSUE TITLE
New version of our Wiki

### ISSUE THREAD

**Issue by aserhany** [Rostlab/DM_CS_WS_2016-17#14]
Dear @lrrichter and @juanmirocks,
We wanted to let you know that we had some changes in our Wiki Page in the last 2 - 3 hours. In case you have already read the old version, we would be very thankful if you can take a look at our new version.
Sorry for the inconvenience 
Link: https://github.com/Rostlab/DM_CS_WS_2016-17/wiki/Week-05-%28W50-Dec14%29-Crimes-in-the-UK
@chaoran-chen @ssoima

**Comment by juanmirocks** [comment]
No issues. Thanks.

**Comment by juanmirocks** [comment]
Just for everybody to know, I myself, review the wikis on early Wednesday morning. Otherwise, I don't mind when you update the wikis.

So far Lothar and I are splitting the reviewing. I do, so far: terrorism, google n-grams, and UK RE.

Lothar I think typically reviews wikis on Tuesday evening.
