### ISSUE TITLE
Feedback to UK Crimes Group

### ISSUE THREAD

**Issue by lrrichter** [Rostlab/DM_CS_WS_2016-17#20]
Good job,

actually what is your current prediction task?

**Comment by aserhany** [comment]
Thanks for the feedback. We are currently focusing on the first prediction goal: To measure the effects of demographic structure on criminal behavior through examining the connection between the demographics of an area and the number of crimes. As advised in our last presentation, we have already chosen 2 area granularities (MSOA and LSOA) for the prediction task. Furthermore we have already finished the data preparation part and have started a linear regression model on the data.
