### ISSUE TITLE
About the Presentation -- Climate Date

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/DM_CS_WS_2016-17#24]
From @magiob 

---

Dear Mr. Cejuela,

One of my team members is coming back from India on Tuesday. I did not know that in advance last Wednesday, thus I asked for my team to present the final project on upcoming Wednesday. However, we will not have enough time to prepare all together the presentation orally which I think it is important for a good presentation. 
If it is possible and it is not trouble for you, could you please move our presentation on February 7th? I apologize for the inconvenience.

Also, I have a question about the final presentation:
- As you told us it should have a story flow. Should we focus more on the conclusions of our work results, and not go in depth to technical aspects like in regular weeks or wiki. For example, should we repeat things like the tactic for our missing values, problems of our data, details about the correlation analysis etc?

I look forward to your reply.

Kind Regards,

Vasileios Magioglou

**Comment by juanmirocks** [comment]
@Rostlab/dm_cs_ws_2016-17 any team presenting on **February 7th** who wants to change to this February 1st ?

I guess it's late for a change.

Otherwise @lrrichter -- what do you think, can we have 4 teams on the 7th? -- I guess it's doable.

**Comment by magiob** [comment]
Her flight was canceled and she is stuck at Abu Dhabi at the moment.

**Comment by juanmirocks** [comment]
@magiob I'm fine with Feb 7th for you guys.

@Rostlab/dm_cs_ws_2016-17 any other team wants to still change?
