### ISSUE TITLE
Some extra feedback :-)

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/DM_CS_WS_2016-17#25]
@chaoran-chen @ssoima @aserhany -- You definitely did a great work.

I suggest, for the slides you showed the number of stop searches and ethnicities by city, to rather normalize by the population of the city to really have rations. I think the point of those slides was to compare the relative probability of for example being stoped if you're asian or caucasian (x2 -- that was very good and very interesting for the police and general public!). So I think normalizing by population size could have made that point stronger and you could have better compared the cities with each other.

Thanks again for the great work throughout the semester and the great imaginative presentations.

**Comment by aserhany** [comment]
Dear @juanmirocks @lrrichter 
Many thanks for the positive feedback. We are very glad that you liked it. We would also like to take this opportunity to thank you for offering this interesting lab course and for your prompt supervision during the whole semester. Also thank you for your suggestions above. We will definitely include it in our final wiki entry.
Best regards,
the whole team @ssoima @chaoran-chen

**Comment by juanmirocks** [comment]
Thank you 😘!
