### ISSUE TITLE
Food Facts Presentation - One member is ill

### ISSUE THREAD

**Issue by Odin94** [Rostlab/DM_CS_WS_2016-17#26]
@juanmirocks @lrrichter

I caught a flu on the weekend and hoped I'd be fine by Wednesday, but as the days progressed it only got worse and I won't be able to hold the presentation. What should we do about this situation? Can we move the presentation to another date or will my teammates have to present without me?

Best regards,
Andreas Kammerloher

**Comment by juanmirocks** [comment]
Thanks Andreas. Hope u get better. Let's wait for Wednesday maybe?
Otherwise I would suggest moving it to next Wednesday. @lrrichter agree?

**Comment by vivek-sethia** [comment]
@juanmirocks @lrrichter
 It will be nice if the presentation can be shifted to next week as I have injured my leg and have a radiology scheduled on Thursday. I have been advised to rest for few days.

Regards,
Vivek Sethia

**Comment by juanmirocks** [comment]
Guys don't die that soon, you have amazing lives ahead

**Comment by juanmirocks** [comment]
🤜
