### ISSUE TITLE
Team Member Distributions

### ISSUE THREAD

**Issue by avradips** [Rostlab/DM_CS_WS_2016-17#4]
Hello,
As it was mentioned that 1 team should have 4 members, but currently I can see that there are two teams with 4 members (one of them being mine). The teams which consist of 4 members are:
* [[Dataset Global Terrorism Database]] @msandim @paulafortuna @kapoorabhishek24 and me
* [[Dataset "Google's N Grams"]] @ImkeHelene @brosequartz @ishaanraj @muhammadasad1 

I hope this is not a problem. 
@juanmirocks @lrrichter

**Comment by juanmirocks** [comment]
Thanks @avradips 

Yes, I saw that last week. It may indeed be problematic. I will try to speak with Lothar @lrrichter  about this before next Wednesday.

What are your thoughts @lrrichter  ?

**Comment by juanmirocks** [comment]
All clear, thank you very much Muhammad @muhammadasad1 

Please also remember to update the team members on your respective dataset wiki pages :-) @avradips @paulafortuna @ImkeHelene @carockets

**Comment by juanmirocks** [comment]
erledigt
