### ISSUE TITLE
Some feedback for Google's N Grams, Week 1

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/DM_CS_WS_2016-17#8]
* i The python library I meant you already listed in your dataset description: https://pypi.python.org/pypi/google-ngram-downloader/
* [ ] Please clearly specify in your dataset whether you are using version 2 or 1 and, then, whether you are using the whole English dataset or just British English or other. I guess this is relevant regarding your choice of the Shakespeare plays dataset.
* watch out: I found non-English grams (e.g. Chinese, Russian, German) in at least both the all English and American English datasets. Therefore, do not disregard the possibility of more mistakes in the dataset. For example:

```
tail -15 googlebooks-eng-all-1gram-20120701-z
заслуживают_NUM	2006	1	1
заслуживают_NUM	2007	1	1
заслуживают_NUM	2008	2	1
中国	1950	1	1
中国	1994	1	1
中国	1997	1	1
中国	2000	5	1
中国	2001	10	1
中国	2002	30	4
中国	2003	105	1
中国	2004	41	4
中国	2005	50	5
中国	2006	95	13
中国	2007	478	38
中国	2008	372	51
```

* bear in mind that Google already filtered uncommon grams (_"we point out that we've included only ngrams that appear over 40 times across the corpus"_). That, therefore, may deprecate the necessity from you of removing abbreviations or other grams as you explained in last presentation.

* [ ] Before you remove/disregard data, make a more thorough analysis of the `only consonant grams`. If only for curiosity:
  * What are they?
  * Are they really artifacts of page numbers or similar as you suggested last time?
  * Could there be relevant `only consonant grams` that are relevant? Example: `Mr., PDF (file format), BTW (by the way), ...` http://www.smart-words.org/abbreviations/texting.html -- Or in older British English: `Mr., cf. (compare), ...`
  * ... something else? 

* [ ] It is not clear to me from the description or from Google's description, what's the first year they have book samples and therefore grams counts from. I presume, as of Version 2, the latest book is of 2012. -- Most importantly, [ ] do really the Google datasets indeed record the epoch of Shakespeare (26 April 1564 - April 1616) ? (or actually _"Shakespeare produced most of his known work between 1589 and 1613"_)

* -> Interesting to investigate is to compare the diction of Shakespeare compared to the general (base rate) diction of his epoch:
  * -> Can you come up with a similarity distance between both?
  * -> since Shakespeare introduced new words and expressions, it's interesting to confirm whether, as expected, he was indeed ahead of his time. In other words, does the similarity distance between his plays and the base rate gradually decreases over time (+ decades or centuries?)
  * -> indeed, the own diction of Shakespeare may have changed over time too. Can you spot this from the data?

* -> I presume (hypothesis), diction changed more slowly in previous centuries than nowadays. Maybe I'm wrong. Can you confirm this? Can you measure exactly the difference of diction between epochs (again, similarity distance).

* i you can bin "epochs" into any bin sizes you may fin most sensible considering your data. Maybe decades, 50 years, 100 years, ... or even, if we confirm that indeed diction evolved faster or slower depending on the epoch, maybe the bin size for previous centuries can be a whole 100 years, while for modern times a more sensible bin size should be 10 years. Don't know. It's interesting to investigate.

* I think you're overdoing the subsectioning. Remove some levels. Also, in my view, numbering is here unnecessary.

* [ ] You barely give information on the _"Transformed"_ dataset of Shakespeare Plays. What is that?

* [ ] Little is know about where and how you collected the Shakespare dataset. This is an essential part of your whole project and should be described in your dataset's main page: update that.

* [ ] "pronouns and determinants are of no use" : why? Provide always explanations, no matter how simple/stupid you think they are. The reader is, by definition, always more stupid than the writer.

* [ ] When you use the term "part of speech", please define. -- Define all special terms, just like you defined n-grams

* Again, always make very clear what you mean with your terms and definitions. For example, it was not immediately obvious at the presentation nor on the wiki description what the "T" data was

* Always sort frequency histograms: easier to read

* -> To go beyond simple word transition statistics of bi-grams, you could, for example, build a simple `hidden markov model (HMM)` to compute, out of only 1-grams or 2-grams the probability of a larger sequence of words and, in turn, the probability of the next word given the whole previous sequence of words.
  * btw, tip: a way for how current models learn better over time is that they learn _individually from you_. That is, instead of using the general base rate of probabilities, current models use or should use _your personalized_ base rate of probabilities. Each one of us use a well constrained set of common words, which are different to other individuals. For most of us, that set of used words is quite very small. Again, compare this to Shakespeare :-)

**Comment by juanmirocks** [comment]
Dear @ImkeHelene and Google's N-Grams teams -- Please find here some feedback from your last presentation and wiki description, and some ideas to consider next.

Happy hacking.

**Comment by ImkeHelene** [comment]
Dear @juanmirocks,

thanks for your feedback. I updated our wikipage but many of the things you asked we mentioned in our presentation, already. 
I would like to suggest something for the weekly meetings: I think - and I also talked to some other course members - that it would be a lot more beneficial if you would let us students hold our presentations first and then afterwards give some feedback. That way the presentations can really only last 7 minutes and you can take 5-7 for each group to give helpful feedback. Could you consider this maybe while preparing the next classes?

Regards,
Imke

**Comment by juanmirocks** [comment]
Thanks @ImkeHelene for your feedback. Yes, we followed that model before too and for the most part I agree with you. Let me discuss it with @lrrichter

Have a great Sunday

**Comment by juanmirocks** [comment]
Closing this now @ImkeHelene
